// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/creator","parentId":"@@/global-layout","id":"2"},"3":{"path":"/ai","parentId":"@@/global-layout","id":"3"},"4":{"path":"/stars","parentId":"@@/global-layout","id":"4"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__home__intro" */'@/pages/home/intro.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__home__creator" */'@/pages/home/creator.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__home__ai" */'@/pages/home/ai.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__home__stars" */'@/pages/home/stars.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/root/data/AI/flyllm/frontend/src/layouts/index.tsx')),
},
  };
}
